version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: learning-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: learning_engine
      MYSQL_USER: springboot
      MYSQL_PASSWORD: springboot123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - learning-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: learning-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - learning-network
    command: redis-server --appendonly yes  # persistencia

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: learning-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # puerto AMQP (Spring)
      - "15672:15672"  # puerto panel web
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - learning-network

  wordpress:
    image: wordpress:latest
    container_name: learning-wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: springboot
      WORDPRESS_DB_PASSWORD: springboot123
      WORDPRESS_DB_NAME: learning_engine
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - learning-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:
  wordpress-data:

networks:
  learning-network:
    driver: bridge