server:
  port: 8081

spring:
  application:
    name: learning-engine
  datasource:
    url: jdbc:mysql://localhost:3309/ingenieria_web
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cache:
    type: redis
    redis:
      time-to-live: 600000

wordpress:
  base-url: http://localhost
  username: luis_04
  password: mBwvqHS4PaQeni9hMiDtQDrt

woocommerce:
  consumer-key: ck_c9ae1c288ffca8e8c28d5b4a3e6ee7610000385b
  consumer-secret: cs_bc94b4887068233c5fdda22aea6385a18d56d8b2

rabbitmq:
  exchanges:
    enrollments: enrollments.exchange
    modules: modules.exchange
  queues:
    enrollment-activated: enrollment.activated.queue
    module-completed: module.completed.queue
  routing-keys:
    enrollment-activated: enrollment.activated
    module-completed: module.completed